apiVersion: v1
kind: Service
metadata:
  name: keycloak-service
  namespace: keycloak-ns
  labels:
    app: keycloak-app
spec:
  ports:
    - name: https-keycloak-external
      port: 443
      targetPort: 8443
  selector:
    app: keycloak-app
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: keycloak-app-deployment
  namespace: keycloak-ns
  labels:
    app: keycloak-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: keycloak-app
  template:
    metadata:
      labels:
        app: keycloak-app
    spec:
      containers:
        - name: keycloak-container
          image: quay.io/keycloak/keycloak:24.0.5
          volumeMounts:
            - name: tls
              mountPath: "/etc/ssl"
              readOnly: true
          args: ["start"]
          env:
            - name: KEYCLOAK_ADMIN
              value: "admin"
            - name: KEYCLOAK_ADMIN_PASSWORD
              value: "admin-123"
            - name: KC_PROXY_HEADERS
              value: "forwarded"
            - name: KC_HOSTNAME
              value: "127.0.0.1.nip.io"
            - name: KC_HOSTNAME_STRICT_HTTPS
              value: "true"
            - name: KC_LOG_LEVEL
              value: "INFO"
            - name: KC_DB
              value: "postgres"
            - name: KC_DB_URL
              value: "jdbc:postgresql://keycloak-postgres-svc:5432/keycloak_db"
            - name: KC_DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: keycloak-postgres-secret
                  key: POSTGRES_USER
            - name: KC_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: keycloak-postgres-secret
                  key: POSTGRES_PASSWORD
            - name: KC_TRANSACTION_XA_ENABLED
              value: "true"
            - name: KC_HEALTH_ENABLED
              value: "true"
            - name: KC_METRICS_ENABLED
              value: "true"
            - name: KC_HTTPS_CERTIFICATE_FILE
              value: /etc/ssl/tls.crt
            - name: KC_HTTPS_CERTIFICATE_KEY_FILE
              value: /etc/ssl/tls.key
          ports:
            - name: http-keycloak
              containerPort: 8443
          readinessProbe:
            httpGet:
              scheme: HTTPS
              path: /realms/master
              port: 8443
            initialDelaySeconds: 180
            periodSeconds: 10
            timeoutSeconds: 20
            failureThreshold: 5
            successThreshold: 1
      volumes:
        - name: tls
          secret:
            secretName: keycloak-tls
            optional: false
